### ISSUE TITLE
Add meson support

### ISSUE THREAD

**Issue by zoziha** [urbanjost/M_CLI2#14]
### Description

Meson has released [version 1.0.0](https://github.com/mesonbuild/meson/releases/tag/1.0.0) and is mature.
M_CLI2 currently supports fpm, **adding Meson build support would be a good option as well**, just like fpm and CMake, Meson is also effective at establishing source file dependencies.

---

Thanks, M_CLI2 works great. I added Meson support for M_CLI2 under [this branch](https://github.com/zoziha/M_CLI2/tree/add-meson-support).
If this sounds good to you @urbanjost , I'll add a PR for that.

**Comment by urbanjost** [comment]
Sounds good.
