### ISSUE TITLE
Adding an option to pass a flag

### ISSUE THREAD

**Issue by awvwgk** [urbanjost/M_CLI2#8]
I just tried adding `--flag` to fpm and found that M_CLI2 won't let me do:

```
fpm run -- build --flag "-O2"
```

As it will result in an unknown short keyword error:

```
UNKNOWN COMPOUND SHORT KEYWORD:O in -O3
KEYWORD    SHORT PRESENT VALUE
version       v  F        [F]
verbose          F        [F]
usage         u  F        [F]
show-model       F        [F]
release          F        [F]
list             F        [F]
help          h  F        [F]
flag             T        [" "]
compiler         F        ["gfortran"]

UNNAMED
000001[build ]
```

Any pointers on how we can elegantly implement this?

**Comment by urbanjost** [comment]
If you end the name with a colon in set_args if means the next field will be taken as a value whether it starts with a - or not.
```fortran
call  setargs(--flags:F: " " ...)
```
means define the long name --flags with the short name -F and the next user input field with be used as an argument no matter what. I added that for a version that had -fc -fflags -fload .. flags but at the time the approach was to try to get something into profiles instead.

**Comment by awvwgk** [comment]
Thanks, this is exactly what I was looking for
